version: "3.7"
services:
  app:
    image: node:12 # Use the full image so we can use node-gyp
    ports:
      - 9999:3000
    links:
      - mysql
    depends_on:
      - data
      - mysql
    environment:
      BUILD_ID: dev
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_USER: apiary
      DB_PASS: db-password
      DB_NAME: apiary
      DB_PORT: 3306
      JWT_SECRET: jwt-secret-token
      VERSION: develop
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    user: node
    restart: on-failure
    command: npm run dev

  data:
    build:
      context: ./data
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./data:/opt/app
    environment:
      DB_HOST: mysql
      DB_USER: apiary
      DB_PASS: db-password
      DB_NAME: apiary
      DB_PORT: 3306
    restart: on-failure

  ##############################
  #  Third-party dependencies  #
  ##############################
  mysql:
    image: mysql
    ports:
      - 9990:3306
    environment:
      MYSQL_DATABASE: apiary
      MYSQL_PASSWORD: db-password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: apiary
    command: --default-authentication-plugin=mysql_native_password
