version: "3.7"
services:
  app:
    image: node:12 # Use the full image so we can use node-gyp
    ports:
      - 3000:3000
    links:
      - mysql
    depends_on:
      - data
      - mysql
    environment:
      BUILD_ID: dev
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_USER: apiary
      DB_PASS: db-password
      DB_NAME: apiary
      DB_PORT: 3306
      DB_MIGRATIONS_RUN: "true"
      DB_SYNC: "false"
      DB_LOGGING: "true"
      DEBUG_BARCODE: "true"
      JWT_SECRET: jwt-secret-token
      LOG_DESTINATION: STDOUT
      LOG_LEVEL: info
      UPLOAD_PATH: /uploads
      VERSION: develop
    working_dir: /opt/app
    volumes:
      - ./uploads:/uploads
      - .:/opt/app
    user: node
    restart: on-failure
    healthcheck:
      # As a dev server, values reflect that app might be (re)building
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    command: npm run dev

  data:
    build:
      context: ./data
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./data:/opt/app
    environment:
      DB_HOST: mysql
      DB_USER: apiary
      DB_PASS: db-password
      DB_NAME: apiary
      DB_PORT: 3306
      UPLOAD_PATH: /uploads
    restart: on-failure

  ##############################
  #  Third-party dependencies  #
  ##############################
  mysql:
    image: mysql
    ports:
      - 9990:3306
    environment:
      MYSQL_DATABASE: apiary
      MYSQL_PASSWORD: db-password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: apiary
    command: --default-authentication-plugin=mysql_native_password
